name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "56db1cce-0556-4a7a-acc7-51fbdaa18212"
database_name = "note-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "c2f36d37b3a546e3a81cba48e14f4b44"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "notes-r2-bucket"
preview_bucket_name = "notes-files-preview"
